#!/bin/bash

# run cmd on nightly
#rustup run nightly rustc --version

rustup show active-toolchain
rustup default stable 
rustup show active-toolchain

#stable-x86_64-pc-windows-msvc (default)
#nightly-x86_64-pc-windows-msvc
